
# site domain
url: http://0.0.0.0:4000

# url to production objects store
digital-objects: https://collectionbuilder.sfo2.cdn.digitaloceanspaces.com/pg1-normalized

# Elasticsearch cluster host
elasticsearch-protocol: https
elasticsearch-host: cb-elasticsearch.derekenos.com
elasticsearch-port: 9200
elasticsearch-index: pg1

exclude: [docs/, Rakefile, README.md, LICENSE, objects/]
