
# site domain
url: http://collectionbuilder-pg1.s3-website-us-east-1.amazonaws.com

# url to production objects store
digital-objects: https://collectionbuilder.sfo2.cdn.digitaloceanspaces.com/pg1-normalized

# Elasticsearch cluster host
elasticsearch-protocol: https
elasticsearch-host: cb-elasticsearch.derekenos.com
elasticsearch-port: 9200
elasticsearch-index: pg1

exclude: [docs/, Rakefile, README.md, LICENSE, objects/]
