
# site domain
url: http://opendata-cityofbeacon.s3-website-us-east-1.amazonaws.com

# url to production objects store
digital-objects: https://datapuddle.nyc3.cdn.digitaloceanspaces.com/cityofbeacon

# Elasticsearch cluster host
elasticsearch-protocol: https
elasticsearch-host: opendata-elasticsearch.derekenos.com
elasticsearch-port: 9200

exclude: [docs/, Rakefile, README.md, LICENSE, objects/]
