
# site domain
url: http://collectionbuilder-uiext.s3-website-us-east-1.amazonaws.com

# url to production objects store
digital-objects: https://collectionbuilder.sfo2.cdn.digitaloceanspaces.com/uiext-normalized

# Elasticsearch cluster host
elasticsearch-protocol: https
elasticsearch-host: cb-elasticsearch.derekenos.com
elasticsearch-port: 9200
elasticsearch-index: uiext

exclude: [docs/, Rakefile, README.md, LICENSE, objects/]
